### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by SteveAmor** [raspberrypilearning/getting-started-with-microbits#5]
Get started broken on 

https://www.raspberrypi.org/learning/getting-started-with-microbit/software/

and What you will need takes you to the wrong page from 

https://www.raspberrypi.org/learning/getting-started-with-microbit/software/

I can't see how to fix this. I guess the page breaks the auto generated website layout?

**Comment by bennuttall** [comment]
Thanks for pointing this out. There was a link from the worksheet to the software page which was generating the software page at `/software/` instead of `/requirements/software/` which meant relative links were broken. Now fixed.

Note: the link above will still yield a broken link, but there's no way to get to that page by clicking through the resource.
